#!/usr/bin/env python
# -*- coding:utf-8 -*-

import os
from collections import defaultdict

gffdic = defaultdict(lambda: defaultdict(list))

def is_overlap(interval1, interval2):
    a, b = interval1
    c, d = interval2
    return a <= d and c <= b

def summarize_gff(mag, gff):
    with open(gff, 'r') as f:
        for line in f:
            if '#' in line:
                continue
            parts = line.strip().split('\t')
            if parts[2] == 'gene':
                gffdic[mag][parts[-1]] = [parts[0], int(parts[3]), int(parts[4])]
    return gffdic

with open('hq.name', 'r') as f:#hq.name: MAG\ttaxonomy information
    for line in f:
        name, tax = line.strip().split('\t')
        gff_path = f"gff/{name}.gff"
        summarize_gff(name, gff_path)

hgts = defaultdict(list)
with open('treefile', 'r') as f:#treefile:a name list of all HGT genes, format: s1,g1\ns1,g2\n...
    for line in f:
        sample, gene = line.strip().split(',')
        hgts[sample].append(gene)

contamination = defaultdict(lambda: defaultdict(list))
with open('totalfcsgx.txt', 'r') as f:#totalfcsgx.txt: a file generated by concatenating the FCS results from all samples. the file format follows that of the FCS-GX results.
    for line in f:
        if '#' in line:
            continue
        parts = line.strip().split('\t')
        contamination[parts[0]][parts[2]] = [int(parts[3]), int(parts[4])]

#All regions flagged by FCS-GX were removed.
for genome in hgts:
    for g in hgts[genome]:
        if g not in gffdic[genome]:
            continue
        contig = gffdic[genome][g][0]
        genename = f"{contig}.{g}"
        genepos = gffdic[genome][g][1:]
        if genename in contamination[genome]:
            print(f"exclude gene----{genome},{contig},{g}")
        if contig in contamination[genome] and is_overlap(genepos, contamination[genome][contig]):
            print(f"exclude contig--{genome},{gffdic[genome][g]},{g}")
